-- Fortify resolved Stripe Price IDs.
-- Additive/non-destructive: maps the existing BRL product catalog to active
-- recurring Stripe prices. Annual recurring prices were created in Stripe test
-- mode because the provided annual products only had one-time prices.

with resolved_plan_catalog (
  id,
  plan_name,
  name,
  slug,
  stripe_product_id,
  stripe_price_id,
  account_limit,
  support_tier,
  billing_interval,
  price_amount,
  currency,
  display_order,
  highlighted,
  recommended_badge,
  plan_features
) as (
  values
    (
      'beginner_monthly',
      'Fortify Beginner Mensal',
      'Beginner',
      'beginner_monthly',
      'prod_UWogmsnDUiFI4b',
      'price_1TfjleFCCIFbGAWBPkdIZmN0',
      1,
      'basic',
      'month',
      9700,
      'brl',
      10,
      false,
      null,
      '["1 conta MT5", "painel de risco", "regras customizaveis", "suporte padrao"]'::jsonb
    ),
    (
      'beginner_annual',
      'Fortify Beginner Anual',
      'Beginner',
      'beginner_annual',
      'prod_Uf3vLt89c3SHly',
      'price_1Tg1CcFCCIFbGAWBKMo9k44G',
      1,
      'basic',
      'year',
      104900,
      'brl',
      20,
      false,
      null,
      '["1 conta MT5", "painel de risco", "regras customizaveis", "suporte padrao"]'::jsonb
    ),
    (
      'advanced_monthly',
      'Fortify Advanced Mensal',
      'Advanced',
      'advanced_monthly',
      'prod_Uf3wnzfJZWD4mh',
      'price_1Tfjp1FCCIFbGAWB5jZ38KB3',
      3,
      'standard',
      'month',
      28700,
      'brl',
      30,
      false,
      null,
      '["ate 3 contas MT5", "multiplas contas", "biblioteca de regras", "plano de gerenciamento"]'::jsonb
    ),
    (
      'advanced_annual',
      'Fortify Advanced Anual',
      'Advanced',
      'advanced_annual',
      'prod_Uf3xj9KBVDBlKC',
      'price_1Tg1CcFCCIFbGAWBvTRLcCx3',
      3,
      'standard',
      'year',
      304900,
      'brl',
      40,
      false,
      null,
      '["ate 3 contas MT5", "multiplas contas", "biblioteca de regras", "plano de gerenciamento"]'::jsonb
    ),
    (
      'pro_monthly',
      'Fortify Pro Mensal',
      'Pro',
      'pro_monthly',
      'prod_Uf3yJK5Nmf7jzw',
      'price_1TfjqlFCCIFbGAWBcYnlMkpB',
      5,
      'priority',
      'month',
      49700,
      'brl',
      50,
      true,
      'Mais escolhido',
      '["ate 5 contas MT5", "suporte prioritario", "insights avancados", "melhor para trader ativo"]'::jsonb
    ),
    (
      'pro_annual',
      'Fortify Pro Anual',
      'Pro',
      'pro_annual',
      'prod_Uf3zoN1lxhobpF',
      'price_1Tg1CdFCCIFbGAWBlzOIIMqA',
      5,
      'priority',
      'year',
      509700,
      'brl',
      60,
      true,
      'Melhor valor',
      '["ate 5 contas MT5", "suporte prioritario", "insights avancados", "melhor para trader ativo"]'::jsonb
    ),
    (
      'enterprise_monthly',
      'Fortify Enterprise Mensal',
      'Enterprise',
      'enterprise_monthly',
      'prod_Uf40eBMaXSHhHx',
      'price_1TfjswFCCIFbGAWBOyP53BGc',
      10,
      'enterprise',
      'month',
      99700,
      'brl',
      70,
      false,
      'VIP',
      '["ate 10 contas MT5", "suporte VIP/Enterprise", "prioridade maxima", "ideal para operacao com varias contas"]'::jsonb
    ),
    (
      'enterprise_annual',
      'Fortify Enterprise Anual',
      'Enterprise',
      'enterprise_annual',
      'prod_Uf41FVIixc7Y33',
      'price_1Tg1CeFCCIFbGAWBwKgdJBiR',
      10,
      'enterprise',
      'year',
      1014700,
      'brl',
      80,
      false,
      'VIP',
      '["ate 10 contas MT5", "suporte VIP/Enterprise", "prioridade maxima", "ideal para operacao com varias contas"]'::jsonb
    )
)
insert into public.plans (
  id,
  plan_name,
  name,
  slug,
  stripe_product_id,
  stripe_price_id,
  status,
  active,
  account_limit,
  support_tier,
  billing_interval,
  price_cents,
  price_amount,
  currency,
  display_order,
  highlighted,
  recommended_badge,
  plan_features
)
select
  id,
  plan_name,
  name,
  slug,
  stripe_product_id,
  stripe_price_id,
  'active',
  true,
  account_limit,
  support_tier,
  billing_interval,
  price_amount,
  price_amount,
  currency,
  display_order,
  highlighted,
  recommended_badge,
  plan_features
from resolved_plan_catalog
on conflict (id) do update set
  plan_name = excluded.plan_name,
  name = excluded.name,
  slug = excluded.slug,
  stripe_product_id = excluded.stripe_product_id,
  stripe_price_id = excluded.stripe_price_id,
  status = excluded.status,
  active = excluded.active,
  account_limit = excluded.account_limit,
  support_tier = excluded.support_tier,
  billing_interval = excluded.billing_interval,
  price_cents = excluded.price_cents,
  price_amount = excluded.price_amount,
  currency = excluded.currency,
  display_order = excluded.display_order,
  highlighted = excluded.highlighted,
  recommended_badge = excluded.recommended_badge,
  plan_features = excluded.plan_features,
  updated_at = now();
