-- Migration desativada: este projeto deve usar exclusivamente as tabelas oficiais já existentes:
-- public.trading_accounts
-- public.mt5_connections
-- public.trades
-- public.open_positions
-- public.account_snapshots
--
-- Não criar tabelas paralelas para o mesmo domínio (trades, posições abertas, snapshots).
