// Fixtures compartilhadas pelos testes do gateway.
import { RULE_BINDING_SCHEMA_VERSION, type AccountRuleBindingRow } from './ruleEngine/bindingTypes';

export function binding(overrides: Partial<AccountRuleBindingRow> = {}): AccountRuleBindingRow {
  return {
    id: 'binding-v1',
    user_id: 'user-a',
    trading_account_id: 'account-a',
    mt5_connection_id: 'connection-a',
    prop_firm_slug: 'firm',
    program_slug: 'firm-2-step',
    account_size_id: 'firm-2-step-100k',
    platform: 'MT5',
    rule_version_id: 'version-1',
    rule_profile_id: 'profile-1',
    rules_last_reviewed_at: '2026-09-01',
    rule_snapshot_hash: 'sha256:v1',
    automatic_monitoring_enabled: true,
    manual_rule_acknowledgement: true,
    manual_rules_status: 'acknowledged',
    binding_status: 'active',
    created_at: '2026-09-01T00:00:00Z',
    updated_at: '2026-09-01T00:00:00Z',
    rule_snapshot: {
      schemaVersion: RULE_BINDING_SCHEMA_VERSION,
      propFirm: { slug: 'firm', name: 'Firm' },
      program: { id: 'p', slug: 'firm-2-step', name: '2-Step', type: '2-Step', market: 'forex' },
      accountSize: { id: 'firm-2-step-100k', label: '$100K', initialBalance: '100000', currency: 'USD' },
      platform: 'MT5',
      version: { id: 'version-1', label: 'v1', effectiveFrom: null, effectiveTo: null, condition: null, notes: [] },
      criticalRules: {
        phases: [{ id: 'phase-1', label: 'Fase 1', profitTarget: '10%' }],
        dailyLoss: '5%',
        maxLoss: '10%',
        drawdownType: 'static',
        drawdownCalculation: 'saldo inicial',
        minTradingDays: '4',
        consistencyRule: 'Não possui',
        newsRule: 'Não possui',
        weekendRule: 'Permitido',
        overnightRule: 'Permitido',
        payoutSplit: '80%',
        firstPayoutTiming: '14 dias',
        maxContracts: 'N/A',
        maxLots: 'N/A',
        leverage: '1:100',
        breachConditions: [],
      },
      monitorability: {
        automaticMt5: ['Perda diária', 'Perda máxima'],
        manualCheck: ['Regra de notícias'],
        notSupportedYet: [],
      },
      evidence: {
        officialSourceUrls: ['https://example.com/rules'],
        confidence: 'high',
        dataCompleteness: 'complete',
        lastReviewedAt: '2026-09-01',
        conflicts: [],
      },
    },
    ...overrides,
  };
}
